### ISSUE TITLE
Crash on MAC

### ISSUE THREAD

**Issue by sharonovd** [tarantool/icu-date#4]
tarantool> icu_date.parse('%Y-%m-%dT%H:%M:%S%z','2018-11-12 08:02:10')
Segmentation fault
  code: SEGV_MAPERR
  addr: 0xc
  context: 0x10881fac8
  siginfo: 0x10881fa60
Current time: 1542010982
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x106382595 in print_backtrace+9
#1  0x1062d8a53 in _ZL12sig_fatal_cbiP9__siginfoPv+158
#2  0x7fff5175af5a in _sigtramp+1a
#3  0x7fff4feda6c6 in _ZN3icu8Calendar5clearEv+80
#4  0x10639b4b4 in lj_vm_ffi_call+84
#5  0x1063d834b in lj_ccall_func+745
#6  0x1063e9bc7 in lj_cf_ffi_meta___call+41
#7  0x106399085 in lj_BC_FUNCC+44
#8  0x1063a951a in lua_pcall+9e
#9  0x106373629 in luaT_call+13
#10 0x10636ecbc in lua_main+59
#11 0x10636ea12 in run_script_f+343
#12 0x1062d8660 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#13 0x106380760 in fiber_loop+2a
#14 0x106484dc6 in coro_init+4b

**Comment by sharonovd** [comment]
Looks like crashes on centos too

**Comment by sharonovd** [comment]
I understand now I've been using it wrong - but segfault does not look like acceptable behaviour
