### ISSUE TITLE
Random crach on MAC

### ISSUE THREAD

**Issue by olegrok** [tarantool/icu-date#6]
It's very strange behaviour. I run tests and sometimes Tarantool crashes with following trace:
```
Segmentation fault
  code: SEGV_MAPERR
  addr: 0x3831303220a7
  context: 0x10981f8b0
  siginfo: 0x10981f848
Current time: 1542962706
Please file a bug at http://github.com/tarantool/tarantool/issues
Attempting backtrace... Note: since the server has already crashed, 
this may fail as well
#0  0x10729709b in print_backtrace+9
#1  0x1071df093 in _ZL12sig_fatal_cbiP9__siginfoPv+158
#2  0x7fff72703b3d in _sigtramp+1d
#3  0x7fff708b93ef in _ZNK3icu12SharedObject9removeRefEv+1b
#4  0x7fff708b4cdb in ucal_open+eb
#5  0x1072b0224 in lj_vm_ffi_call+84
#6  0x1072ecea9 in lj_ccall_func+74b
#7  0x1072fe65e in lj_cf_ffi_meta___call+41
#8  0x1072addf5 in lj_BC_FUNCC+44
#9  0x1072bdfa3 in lua_pcall+9b
#10 0x107287c72 in luaT_call+13
#11 0x10728386b in lua_main+57
#12 0x10728354a in run_script_f+2cd
#13 0x1071deca6 in _ZL16fiber_cxx_invokePFiP13__va_list_tagES0_+c
#14 0x10729525d in fiber_loop+2a
#15 0x1073b4bf2 in coro_init+4b
```

I will try to add script for reproduce it, but it happens very rarely.

**Comment by olegrok** [comment]
```
icu_date = require('icu-date')
for i=1,10000 do
    date = icu_date.new()
    format = icu_date.formats.pattern("d MMMM y", 'ru_RU')
    date:format(format)
end
```

**Comment by olegrok** [comment]
Sometimes it happens:
```
tarantool(76467,0x10a7da5c0) malloc: Incorrect checksum for freed object 0x7fb3fb61a9c0: probably modified after being freed.
Corrupt value: 0x800038313032208f
tarantool(76467,0x10a7da5c0) malloc: *** set a breakpoint in malloc_error_break to debug
```

**Comment by filonenko-mikhail** [comment]
reproduced

**Comment by olegrok** [comment]
Can't reproduce on 1.10.3-19-g37df35b73/1.10.3-33-gfd303466c/2.1.1-609-ga00169714

May be https://github.com/tarantool/tarantool/commit/e5e259a82f8ef771818b97f5f8ca8ab601e9e2c4 or https://github.com/tarantool/tarantool/commit/a445cdfa8157df8be9b52e4fa1297297671b7a2b fixed the problem

@filonenko-mikhail 
Can you check, please?

**Comment by filonenko-mikhail** [comment]
not reproduced
